### ISSUE TITLE
`AbstractMethodError` with Gradle 8.1

### ISSUE THREAD

**Issue by DanySK** [koral--/jacoco-gradle-testkit-plugin#27]
Applying the latest plugin with Gradle 8.1 causes a failure.
I'm attaching a build scan to help debug the issue

https://scans.gradle.com/s/wwecwzx6fceew/failure?expanded-stacktrace=WyIwLTEtMiJd#1

**Comment by koral--** [comment]
It should be fixed in version 1.0.10 (pending approval on Gradle plugin at the time of writing).

**Comment by DanySK** [comment]
Is something going wrong? Usually the gradle plugin portal takes a few minutes at most to approve a plugin...

**Comment by koral--** [comment]
I have never encountered such status personally, despite that I have published several plugins, each one in many versions.
I've contacted support.

**Comment by DanySK** [comment]
Thank you. Keep us posted :)

**Comment by mateuszkwiecinski** [comment]
FYI, the 1.0.10 is now [available](https://plugins.gradle.org/m2/pl/droidsonroids/gradle/jacoco/pl.droidsonroids.gradle.jacoco/1.0.10/), but it has broken <17 Java compatibility :/ 
So if your build uses Java 17 or above you should be fine with 1.0.10, if not then the compatibility should be restored by https://github.com/koral--/jacoco-gradle-testkit-plugin/pull/29 🤞

**Comment by DanySK** [comment]
I run tests in all the Java versions supported by Gradle when i develop
plugins... I guess I'll wait a bit more
