### ISSUE TITLE
Support of Gradle 7.6 is broken

### ISSUE THREAD

**Issue by nulls** [koral--/jacoco-gradle-testkit-plugin#31]
Hi,

The [diktat](https://github.com/saveourtool/diktat) uses `jacoco-gradle-testkit-plugin` and we get an error after upgrading to latest version `v.1.0.11`. We still use Gradle 7.6.

As I can see, the plugin migrated from custom task `GenerateJaCoCoTestKitProperties` to Gradle's one `WriteProperties` in scope of https://github.com/koral--/jacoco-gradle-testkit-plugin/pull/26, because the property `destinationFile` was added to `WriteProperties` in Gradle 8.x.

It breaks the plugin on Gradle 7.6 when `pl.droidsonroids.gradle.jacoco.testkit.JacocoTestKitExtension#applyTo` is used:
```
* What went wrong:
A problem occurred configuring root project 'junit14383727692287311849'.
> Could not create task ':generateJacocoIntegrationTestKitProperties'.
   > 'org.gradle.api.file.RegularFileProperty org.gradle.api.tasks.WriteProperties.getDestinationFile()'
```

The plugin has a test to check compatibility with Gradle 7.6, but this test doesn't call method from `JacocoTestKitExtension`.
But if change Gradle version in the test `gradle properties file generated for a custom task` -- it will fail.

**Comment by koral--** [comment]
Thanks for the report. I've also updated the unit test to actually perform a check.
